version: '3'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        links:
            - xray
        environment:
            XRAY_DAEMON_ADDRESS: xray:2000
            AWS_REGION: us-east-2


    xray:
        image: amazon/aws-xray-daemon
        entrypoint: /usr/bin/xray --local-mode -o
